export { default as DashboardView } from './DashboardView.vue'
export { default as ProfileView } from './ProfileView.vue'
export { default as MyApplicationsView } from './MyApplicationsView.vue'
export { default as MyCoursesView } from './MyCoursesView.vue'
export { default as StudentApplicationsView } from './StudentApplicationsView.vue'
export { default as AccessDeniedView} from '../../AccessDeniedView.vue'
export { default as MyModulesView } from './MyModulesView.vue'
export { default as ApplyForCourseView } from './ApplyForCourseView.vue'
export { default as CourseView } from './CourseView.vue'
export { default as AllCoursesView } from './AllCoursesView.vue'
export { default as CreateCourseView } from './CreateCourseView.vue'
export { default as ModerateCourseView } from './ModerateCourseView.vue'
export { default as CreateModuleView } from './CreateModuleView.vue'
export { default as ModuleView } from './ModuleView.vue'
export { default as ModerateModuleView } from './ModerateModuleView.vue'
export { default as LectureView } from './LectureView.vue'
export { default as ModeratorCoursesView } from './ModeratorCoursesView.vue'