export { default as DashboardView } from './DashboardView.vue'
export { default as ProfileView } from './ProfileView.vue'
export { default as MyApplicationsView } from './MyApplicationsView.vue'
export { default as MyCoursesView } from './MyCoursesView.vue'
export { default as StudentApplicationsView } from './StudentApplicationsView.vue'
export { default as AccessDeniedView} from './AccessDeniedView.vue'
export { default as MyModulesView } from './MyModulesView.vue'