export { default as ErrorModal } from './ErrorModal.vue'
export { default as ConfirmDialog } from './ConfirmDialog.vue'
export { default as InnerErrorModal } from './InnerErrorModal.vue'
export { default as AddPostDialog } from './AddPostDialog.vue'
export { default as DropFileDialog } from './DropFileDialog.vue'