version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: cos720
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-boot-postgres

  backend:
    build: server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      APP_KEY: ${JWT_KEY}
      APP_TOKEN_EXPIRE_FACTOR: "90"
      APP_CONNECTION_TIMEOUT: "3000"
      APP_REQUEST_TIMEOUT: "3000"
    networks:
      - spring-boot-postgres
      - spring-boot-react
  frontend:
      build:
        context: ./client
        dockerfile: Dockerfile
      depends_on:
        - backend
      ports:
        - "3000:80"
      networks:
        - spring-boot-react

volumes:
  postgres-data:

networks:
  spring-boot-postgres:
  spring-boot-react: