version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: cos720
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - server-db

  server:
    build: ./server
    container_name: "server"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      APP_KEY: ${JWT_KEY}
      APP_TOKEN_EXPIRE_FACTOR: "90"
      APP_CONNECTION_TIMEOUT: "3000"
      APP_REQUEST_TIMEOUT: "3000"
    networks:
      - proxy-server
      - server-db
  
  client:
    build: ./client
    container_name: "client"
    depends_on:
      - server
    networks:
      - proxy-client
      

  proxy:
    build: ./nginx
    container_name: "proxy"
    restart: always
    ports:
      - "80:80"
    networks:
      - proxy-client
      - proxy-server

volumes:
  postgres-data:

networks:
  proxy-client:
  proxy-server:
  server-db: