spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        formatsql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
app.key: ${JWT_SIGNING_KEY}
app.token.expire.factor: 90
app.connection.timeout: 3000
app.request.timeout: 3000
app.encryption.key: ${ENCRYPTION_KEY}