export * from './home'
export { default as LoginView } from './LoginView.vue'
export { default as ApplyView } from './ApplyView.vue'
export { default as ConfirmationView } from './ConfirmationView.vue'
export { default as VerifyView } from './VerifyView.vue'
export { default as NotFoundView } from './NotFoundView.vue'
export { default as AccessDeniedView } from './AccessDeniedView.vue'
export { default as UnderConstructionView } from './UnderConstructionView.vue'
export { default as ForgotPasswordView } from './ForgotPasswordView.vue'
export { default as ResetPasswordView } from './ResetPasswordView.vue'
