export * from './home'
export { default as LoginView } from './LoginView.vue'
export { default as ApplyView } from './ApplyView.vue'
export { default as ConfirmationView } from './ConfirmationView.vue'
export { default as VerifyView } from './VerifyView.vue'
