name: Push Server

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ 'main' ]

jobs:
  docker:
    name: Docker Build and Push Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace placeholders in application.yml
        run: |
          sed -i "s|\${DATABASE_URL}|$DATABASE_URL|g" server/src/main/resources/application.yml
          sed -i "s|\${DATABASE_USERNAME}|$DATABASE_USERNAME|g" server/src/main/resources/application.yml
          sed -i "s|\${DATABASE_PASSWORD}|$DATABASE_PASSWORD|g" server/src/main/resources/application.yml
          sed -i "s|\${JWT_SIGNING_KEY}|$JWT_SIGNING_KEY|g" server/src/main/resources/application.yml
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          JWT_SIGNING_KEY: ${{ secrets.JWT_SIGNING_KEY }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push SERVER
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/project-server:latest