name: Server

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches: [ 'main' ]

jobs:
  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest

    env:
      APPLICATION_YML_CONTENT: ${{ secrets.SERVER_APPLICATION_YML }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Decrypt and Load Application YML Content
        run: echo "${{ secrets.APPLICATION_YML_CONTENT }}" > application.yml

      - name: Build and push SERVER
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/project-server:latest