name: OWASP ZAP Security Testing

on:
    workflow_dispatch:

jobs:
    baseline:
      runs-on: ubuntu-latest
      name: ZAP Baseline Scan
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        
        - name: ZAP API Scan
          uses: zaproxy/action-api-scan@v0.7.0
          with:
            target: ${{secrets.HOST_URL}}

    full:
      runs-on: ubuntu-latest
      name: ZAP Full Scan
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        
        - name: ZAP API Scan
          uses: zaproxy/action-full-scan@v0.10.0
          with:
            target: ${{secrets.HOST_URL}}

            