name: OWASP ZAP Security Testing

on:
    push:
      branches:
        - main
        - dev
    pull_request:
      branches:
        - main

jobs:
    test-spring:
        runs-on: ubuntu-latest
        name: ZAP baseline test
        env:
            SPRING_MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
            APP_ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
            APP_ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
            APP_ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
            APP_ADMIN_NAME_FIRST: Nathan
            APP_ADMIN_NAME_LAST: Opperman
            APP_BASE_URL: http://localhost:3000
            APP_KEY: ${{secrets.JWT_SIGNING_KEY }}
            APP_ENCRYPTION_KEY: ${{ secrets.DATABASE_ENCRYPTION_KEY }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Set JDK
              uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'temurin'

            # Bulding springboot application with a different maven profile to bring H2 database into runtime scope
            - name: Build Mvn Application
              run: mvn clean install -Ptest -DskipTests
            
            # Running the JAR with the test configuration, runs in background
            - name: Run Spring Jar
              run: java -jar -Dspring.profiles.active=test target/server-0.0.1-SNAPSHOT.jar &
            
            - name: ZAP API Scan
              uses: zaproxy/action-api-scan@v0.7.0
              with:
                target: 'http://localhost:8080/api/v1'

            