name: OWASP ZAP Security Testing

on:
    push:
      branches:
        - main
        - dev
    pull_request:
      branches:
        - main

jobs:
    test-spring:
        runs-on: ubuntu-latest
        name: ZAP baseline test
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: ZAP API Scan
              uses: zaproxy/action-api-scan@v0.7.0
              with:
                target: 'http://localhost:3000/api/v1'

            