name: OWASP ZAP Security Testing

on:
    push:
      branches:
        - main
        - dev
    pull_request:
      branches:
        - main

jobs:
    test-spring:
        runs-on: ubuntu-latest
        name: ZAP baseline test
        env:
            SPRING_PROFILES_ACTIVE: prod
            SPRING_DATASOURCE_URL: ${{ secrets.TEST_DATABASE_URL}}
            SPRING_DATASOURCE_USERNAME: ${{ secrets.TEST_DATABASE_USERNAME }}
            SPRING_DATASOURCE_PASSWORD: ${{ secrets.TEST_DATABASE_PASSWORD }}
            SPRING_MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
            APP_ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
            APP_ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
            APP_ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
            APP_ADMIN_NAME_FIRST: Nathan
            APP_ADMIN_NAME_LAST: Opperman
            APP_BASE_URL: http://localhost
            APP_KEY: ${{secrets.JWT_SIGNING_KEY }}
            APP_ENCRYPTION_KEY: ${{ secrets.DATABASE_ENCRYPTION_KEY }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Set JDK
              uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'temurin'

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'
            
            - name: Build
              run: mvn -B package -DskipTests --file ./server/pom.xml
      
            - name: Build Vue.js Application
              run: |
                cd client
                npm install
                VITE_APP_API_KEY=http://localhost:8080/api/v1
                npm run build
      
            # Serve the built Vue.js application
            - name: Serve Vue.js Application
              run: |
                cd client/dist
                npx serve &
              continue-on-error: true

            - name: Run Spring Application
              run: java -jar ./server/target/server-0.0.1-SNAPSHOT.jar &
            
            - name: ZAP Baseline Scan
              uses: zaproxy/action-baseline@v0.12.0
              with:
                target: 'http://localhost:3000/'

            